Add proposed LSP 3.16 changes
eclipse/lsp4j pull request #456
Opened 2020-10-20 00:14 UTC by KamasamaK

Some of the larger proposed LSP 3.16 changes such as call hierarchy and semantic token support have already been added or are in progress. I have bundled most of the remaining changes here. They include:

* Add client capability for resolving text edits on completion items.
* Add client capability for using client default behavior on renames. (The new `prepareRename` result still needs to be implemented)
* Add support for insert and replace ranges on `CompletionItem`.
* Add support for diagnostic code descriptions.
* Add support for tags on `SymbolInformation` and `DocumentSymbol` and deprecated the standalone `deprecated` properties.
* Add support for code action `disabled` property.
* Add support for code action resolve request.
* Add support for diagnostic `data` property.
* Add support for signature information `activeParameter` property.

There are also some minor changes to comments or format.

2020-10-20 07:27 UTC, Dufgui commented
Huge and wonderfull work. Hyper clean ;o)

I think we can add "since" on:
- CallHierarchyPrepareParams  
- CallHierarchyIncomingCallsParams
- CallHierarchyOutgoingCallsParams 
- CallHierarchyIncomingCall 
- CallHierarchyOutgoingCall 
- CallHierarchyItem

2020-10-20 07:28 UTC, Dufgui requested changes
Huge and wonderfull work. Hyper clean ;o)

I think we can add "since" on:
- CallHierarchyPrepareParams  
- CallHierarchyIncomingCallsParams
- CallHierarchyOutgoingCallsParams 
- CallHierarchyIncomingCall 
- CallHierarchyOutgoingCall 
- CallHierarchyItem

2020-10-20 07:28 UTC, Dufgui commented on org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/Protocol.xtend
> + */
```suggestion
 * Since 3.16.0
 */
```

2020-10-20 07:28 UTC, Dufgui commented on org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/Protocol.xtend
> + */
I see you already put it when it's use, not sure, it's usefull their.

2020-10-20 07:28 UTC, Dufgui commented on org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/Protocol.xtend
>   */
```suggestion
 * Since 3.16.0
 */
```

2020-10-20 07:34 UTC, Dufgui commented
maybe we can add the Since in `TextDocumentService ` for callHierarchy calls ?

2020-10-26 10:06 UTC, spoenemann approved these changes
Great, thank you!

2020-10-26 11:14 UTC, merged